name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build executables
        run: bun run build

      - name: Compress executables
        run: |
          zip -9 recipe_manager_macos.zip recipe_manager
          zip -9 recipe_manager_windows.zip recipe_manager.exe

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: recipe-manager-executables
          path: |
            recipe_manager_macos.zip
            recipe_manager_windows.zip
          retention-days: 7

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            recipe_manager_macos.zip
            recipe_manager_windows.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}